name: BedWars1058-SpectatorOptions
version: '${project.version}'
main: me.cubecrafter.spectatoroptions.SpectatorOptions
api-version: 1.13
author: CubeCrafter
description: Add useful settings for spectators!
depend:
  - BedWars1058